# Generated by Django 3.0.5 on 2021-09-11 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECARGA', 'RGA'), ('PAGO', 'PAG'), ('ENVIO', 'ENV'), ('RECIBO', 'REC'), ('MENSAJE', 'MSJ'), ('REGISTRO', 'NEW')], max_length=10)),
                ('contenido', models.CharField(max_length=250)),
                ('vista', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('imagen', models.ImageField(default='usuario/default.jpg', upload_to=users.models.upload_to, verbose_name='Image')),
                ('sync', models.BooleanField(default=False)),
                ('notificaciones', models.ManyToManyField(to='users.Notificacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
