# Generated by Django 3.0.5 on 2021-05-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210428_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sync',
            field=models.BooleanField(default=False),
        ),
    ]
