# Generated by Django 3.0.5 on 2021-07-11 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210710_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 4, 54, 36, 320329, tzinfo=utc)),
        ),
    ]
