# Generated by Django 3.0.5 on 2021-07-13 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210713_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
