# Generated by Django 3.0.5 on 2021-08-17 20:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210713_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='usuario/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
