# Generated by Django 3.0.5 on 2021-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
