# Generated by Django 3.0.5 on 2021-03-21 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_auto_20210320_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='servicio',
            field=models.CharField(default='internet', max_length=15),
            preserve_default=False,
        ),
    ]
