# Generated by Django 3.0.5 on 2021-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_sorteodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteodetalle',
            name='fecha',
        ),
        migrations.AddField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=4, max_length=10),
        ),
    ]
