# Generated by Django 3.0.5 on 2021-04-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_auto_20210428_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteodetalle',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
