# Generated by Django 3.0.5 on 2021-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_sorteodetalle_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteodetalle',
            name='ganador',
            field=models.CharField(default='me', max_length=40),
            preserve_default=False,
        ),
    ]
