# Generated by Django 3.0.5 on 2021-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_sorteodetalle_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteodetalle',
            name='recarga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='ganador',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
