# Generated by Django 3.0.5 on 2021-04-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_auto_20210429_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=4, max_length=10),
        ),
    ]
