# Generated by Django 3.0.5 on 2021-06-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0008_auto_20210507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=6, max_length=10),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=6, max_length=10),
        ),
    ]
