# Generated by Django 3.0.5 on 2021-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0009_auto_20210606_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='mes',
            field=models.CharField(default=7, max_length=10),
        ),
        migrations.AlterField(
            model_name='sorteodetalle',
            name='mes',
            field=models.CharField(default=7, max_length=10),
        ),
    ]
