# Generated by Django 3.0.5 on 2021-07-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('ip_online', models.GenericIPAddressField()),
                ('internet', models.BooleanField(default=False)),
                ('ip_internet', models.GenericIPAddressField()),
                ('jc', models.BooleanField(default=False)),
                ('ip_jc', models.GenericIPAddressField()),
                ('emby', models.BooleanField(default=False)),
                ('ip_emby', models.GenericIPAddressField()),
                ('ftp', models.BooleanField(default=False)),
                ('ip_ftp', models.GenericIPAddressField()),
            ],
        ),
    ]
