# Generated by Django 3.0.5 on 2021-07-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_estadoconexion_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoconexion',
            name='servidor',
            field=models.CharField(default='iVan', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_emby',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_ftp',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_internet',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_jc',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_online',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
