# Generated by Django 3.0.5 on 2021-07-19 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20210713_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoconexion',
            name='fecha_internet',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
