# Generated by Django 3.0.5 on 2021-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_estadoconexion_fecha_internet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconexion',
            name='fecha_internet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
