# Generated by Django 3.0.5 on 2021-04-28 20:25

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen2',
            field=models.ImageField(default='forum/image1.png', upload_to=forum.models.upload_to, verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen3',
            field=models.ImageField(default='forum/image1.png', upload_to=forum.models.upload_to, verbose_name='Image3'),
        ),
    ]
