# Generated by Django 3.0.5 on 2021-06-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion1', models.CharField(max_length=60)),
                ('opcion2', models.CharField(max_length=60)),
                ('opcion3', models.CharField(max_length=60)),
                ('opcion4', models.CharField(max_length=60)),
                ('opcion5', models.CharField(max_length=60)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Publicacion')),
                ('voto1', models.ManyToManyField(related_name='Opcion1', to=settings.AUTH_USER_MODEL)),
                ('voto2', models.ManyToManyField(related_name='Opcion2', to=settings.AUTH_USER_MODEL)),
                ('voto3', models.ManyToManyField(related_name='Opcion3', to=settings.AUTH_USER_MODEL)),
                ('voto4', models.ManyToManyField(related_name='Opcion4', to=settings.AUTH_USER_MODEL)),
                ('voto5', models.ManyToManyField(related_name='Opcion5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Publicacion')),
            ],
        ),
    ]
