# Generated by Django 3.0.5 on 2021-06-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comentario_encuesta_respuestacomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Publicacion'),
        ),
    ]
