# Generated by Django 3.0.5 on 2021-06-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210428_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tema',
            field=models.CharField(choices=[('Noticia', 'Noticia'), ('Internet', 'Internet'), ('JovenClub', 'JovenClub'), ('Emby', 'Emby'), ('FileZilla', 'FileZilla'), ('QbaRed', 'QbaRed')], max_length=15),
        ),
    ]
