# Generated by Django 3.0.5 on 2021-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210606_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
