# Generated by Django 3.0.5 on 2021-06-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210609_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Publicacion'),
            preserve_default=False,
        ),
    ]
