# Generated by Django 3.0.5 on 2021-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_publicacion_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='vistas',
            field=models.PositiveIntegerField(),
        ),
    ]
