# Generated by Django 3.0.5 on 2021-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210608_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='vistas',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
