# Generated by Django 3.0.5 on 2021-06-08 19:08

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20210608_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen1',
            field=models.ImageField(default='forum/image1.png', upload_to=forum.models.upload_to, verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen2',
            field=models.ImageField(default='forum/image1.png', upload_to=forum.models.upload_to, verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen3',
            field=models.ImageField(default='forum/image1.png', upload_to=forum.models.upload_to, verbose_name='Imagen3'),
        ),
    ]
