# Generated by Django 3.0.5 on 2021-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20210608_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
