# Generated by Django 3.0.5 on 2022-01-21 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='destinos',
            field=models.ManyToManyField(related_name='destinos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
