# Generated by Django 3.0.5 on 2021-03-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import servicios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=servicios.models.codigoRecarga, max_length=10, unique=True)),
                ('cantidad', models.IntegerField()),
                ('fechaHecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('fechaUso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('servicio', models.CharField(blank=True, max_length=15, null=True)),
                ('codRec', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(default=servicios.models.generarHash, max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('RECARGA', 'RGA'), ('PAGO', 'PAG'), ('ENVIO', 'ENV'), ('RECIBO', 'REC')], max_length=10)),
                ('haciaDesde', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.BooleanField(default=False)),
                ('int_time', models.DateTimeField(blank=True, null=True)),
                ('int_horas', models.IntegerField(blank=True, null=True)),
                ('int_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('int_auto', models.BooleanField(default=False)),
                ('emby', models.BooleanField(default=False)),
                ('emby_time', models.DateTimeField(blank=True, null=True)),
                ('emby_id', models.CharField(blank=True, max_length=50, null=True)),
                ('emby_auto', models.BooleanField(default=False)),
                ('jc', models.BooleanField(default=False)),
                ('jc_time', models.DateTimeField(blank=True, null=True)),
                ('jc_auto', models.BooleanField(default=False)),
                ('ftp', models.BooleanField(default=False)),
                ('ftp_time', models.DateTimeField(blank=True, null=True)),
                ('ftp_auto', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
