# Generated by Django 3.0.5 on 2021-05-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210521_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoservicio',
            old_name='emby_sync',
            new_name='sync',
        ),
        migrations.RemoveField(
            model_name='estadoservicio',
            name='ftp_sync',
        ),
        migrations.RemoveField(
            model_name='estadoservicio',
            name='int_sync',
        ),
        migrations.RemoveField(
            model_name='estadoservicio',
            name='jc_sync',
        ),
    ]
