# Generated by Django 3.0.5 on 2024-02-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.CharField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], max_length=20)),
                ('year', models.IntegerField(default=2024)),
                ('days', models.IntegerField()),
                ('gross_income', models.IntegerField()),
                ('total_spent', models.IntegerField()),
                ('income', models.IntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('spent', models.IntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.MonthIncome')),
            ],
        ),
    ]
