# Generated by Django 3.0.5 on 2024-02-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20240212_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=30)),
                ('month', models.IntegerField(default=2)),
                ('year', models.IntegerField(default=2024)),
                ('total', models.IntegerField(default=0)),
                ('seller_profit', models.IntegerField(default=0)),
                ('admin_share', models.IntegerField(default=0)),
            ],
        ),
    ]
